"use strict";
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'..');
const catalogue=JSON.parse(fs.readFileSync(path.join(root,'data/homepage.json'),'utf8'));
const metadata=JSON.parse(fs.readFileSync(path.join(root,'data/entity-types.json'),'utf8'));
const presentation=JSON.parse(fs.readFileSync(path.join(root,'data/presentation.json'),'utf8'));
const firstPage=catalogue.entities.slice(0,presentation.page_size);
const feed=JSON.parse(fs.readFileSync(path.join(root,'data/active-pages.json'),'utf8'));
const matches=(entity,query)=>[entity.id,entity.title,entity.subtitle,entity.description,metadata.records[entity.id].type,metadata.records[entity.id].purpose,...metadata.records[entity.id].audience,...metadata.records[entity.id].roles,...entity.releases.map(r=>[r.id,r.label,r.url,r.status,r.source_ref].join(' '))].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase());
const output=path.join(root,'browser-evidence');fs.mkdirSync(output,{recursive:true});
const isApp=url=>{const h=new URL(url).hostname;return !/(^|\.)github\.com$/i.test(h)&&!/(^|\.)githubusercontent\.com$/i.test(h);};
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{let browser;const receipt={status:'running',checks:[],source:process.env.GITHUB_SHA||'local'};try{
if(process.platform==='win32'&&!process.env.ALLOW_LOCAL_BROWSER)throw Error('Use hosted Linux browser verification; local Windows launch disabled.');
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.waitForSelector('.development-track');
assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');
assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');
assert.equal(await page.locator('.brand').evaluate(e=>getComputedStyle(e).color),'rgb(102, 204, 255)');
assert.equal(await page.locator('#archiveLink').evaluate(e=>getComputedStyle(e).color),'rgb(102, 204, 255)');
assert.equal(await page.locator('#kuiper').evaluate(e=>getComputedStyle(e).borderTopColor),'rgb(51, 51, 51)');
assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily.replace(/\s/g,'')),'ui-monospace,SFMono-Regular,Consolas,monospace');
assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).fontSize),'16px');
assert.equal(await page.locator('h1').evaluate(e=>getComputedStyle(e).fontWeight),'500');
assert.equal(await page.locator(':root').evaluate(e=>getComputedStyle(e).getPropertyValue('--cyan').trim()),'#00ffff');
receipt.checks.push('historical black/white/blue/cyan palette, grey borders and unchanged fonts');
assert.equal(await page.locator('#nests > details').count(),catalogue.view.items.length);
assert.equal(await page.locator('#kuiper').evaluate(e=>e.open),false);
assert.equal(await page.locator('.build-card,.build-highlights,.ticker-pause').count(),0);
assert.equal(await page.getByRole('button',{name:/pause|resume/i}).count(),0);
assert.equal(await page.locator('.development-group:not([aria-hidden]) a').count(),feed.items.length);
assert.deepEqual(await page.locator('.development-group:not([aria-hidden]) a').allTextContents(),feed.items.map(i=>i.label));
for(const href of await page.locator('a[href]').evaluateAll(items=>items.map(a=>a.href)))assert(isApp(href),'Only app links: '+href);
assert.equal(await page.locator('.release-url,.build-evidence').count(),0);
receipt.checks.push('closed Kuiper, no In build or pause controls, label-only live app ticker');
assert.deepEqual(await page.locator('.highlight-card').evaluateAll(cards=>cards.map(card=>card.dataset.entityId)),presentation.highlights.map(item=>item.entity_id));
assert.deepEqual(await page.locator('.highlight-label').allTextContents(),presentation.highlights.map(item=>item.label));
for(const item of presentation.highlights){const entity=catalogue.entities.find(e=>e.id===item.entity_id);assert.equal(await page.locator('.highlight-card[data-entity-id='+JSON.stringify(item.entity_id)+']').getAttribute('href'),entity.releases.find(r=>r.id===entity.operative_release_id).url);}
assert(await page.evaluate(()=>Boolean(document.getElementById('highlights').compareDocumentPosition(document.querySelector('.development-strip'))&Node.DOCUMENT_POSITION_FOLLOWING)));
receipt.checks.push('four curated app destinations precede the activity ticker');
assert(await page.evaluate(()=>Boolean(document.getElementById('catalogue').compareDocumentPosition(document.getElementById('nests'))&Node.DOCUMENT_POSITION_FOLLOWING)));
assert.equal(await page.locator('.highlight-card').first().evaluate(e=>getComputedStyle(e).borderTopWidth),'0px');
receipt.checks.push('plain text highlights and searchable table precede secondary section browsing');
assert.equal(await page.locator('#catalogueRows tr').count(),firstPage.length);
for(const entity of firstPage){const row=page.locator('#catalogueRows tr').filter({has:page.getByRole('link',{name:entity.title,exact:true})});assert.equal(await row.count(),1);assert.equal(await row.getAttribute('data-entity-id'),entity.id);const release=entity.releases.find(r=>r.id===entity.operative_release_id);assert.equal(await row.locator('th a').getAttribute('href'),release.url);assert.equal(await row.locator('.table-versions > summary').innerText(),release.label);}
await page.locator('#catalogueRows a').first().focus();assert.equal(await page.locator('#catalogueRows a').first().evaluate(e=>e===document.activeElement),true);
receipt.checks.push('all catalogue entities share current release links, persistent IDs and keyboard access');
assert.equal(await page.locator('#catalogueRows .table-versions .release').count(),0);
assert.equal(await page.locator('#kuiper .versions .release').count(),0);
await page.locator('#catalogueRows .table-versions > summary').first().click();
assert.match(await page.locator('#catalogueRows tr').first().innerText(),new RegExp(catalogue.entities[0].operative_release_id));
assert.equal(await page.locator('#catalogueRows .entity-key').first().innerText(),catalogue.entities[0].id);
await page.locator('#catalogueRows .table-versions > summary').first().click();
await page.locator('#catalogueRows .table-versions > summary').first().click();
assert.equal(await page.locator('#catalogueRows tr').first().locator('.table-versions .release').count(),catalogue.entities[0].releases.length);
await page.locator('#catalogueRows .table-versions > summary').first().click();
receipt.checks.push('release detail DOM is created on demand and reused without duplicates');
const search=page.locator('#homepageSearch');assert((await search.boundingBox()).y<(await page.locator('#nests').boundingBox()).y);
await search.fill('GridAtlas');assert.equal(await page.locator('#catalogueRows tr:visible').count(),catalogue.entities.filter(e=>matches(e,'GridAtlas')).length);assert.equal(await page.locator('#gridatlas').isVisible(),true);
await search.fill('unlikelynomatch');assert.match(await page.locator('#searchStatus').innerText(),/No matching/);
assert.equal(await page.locator('#catalogueRows tr:visible').count(),0);assert.equal(await page.locator('#catalogueEmpty').isVisible(),true);
await search.fill('');assert.equal(await page.locator('#nests > details:visible').count(),catalogue.view.items.length);assert.equal(await page.locator('#kuiper').evaluate(e=>e.open),false);
assert.equal(await page.locator('#catalogueRows tr:visible').count(),firstPage.length);assert.equal(await page.locator('#catalogueEmpty').isVisible(),false);
receipt.checks.push('top search filters nests and table, shows empty state and restores closed nests');
assert.deepEqual(Object.keys(metadata.records).sort(),catalogue.entities.map(e=>e.id).sort());
for(const meta of Object.values(metadata.records))assert(['engine','application','dataset','equipment','project','reference','drawing','catalogue'].includes(meta.type));
await search.fill('engine');assert.deepEqual(await page.locator('#catalogueRows tr').evaluateAll(rows=>rows.map(row=>row.dataset.entityId)),catalogue.entities.filter(entity=>matches(entity,'engine')).slice(0,presentation.page_size).map(entity=>entity.id));
await search.fill('proposal-authoring');assert.deepEqual(await page.locator('#catalogueRows tr').evaluateAll(rows=>rows.map(row=>row.dataset.entityId)),['kuiper']);
await page.locator('#catalogueRows .entity-type > summary').click();assert.match(await page.locator('#catalogueRows .entity-type').innerText(),/Intended purpose:/);assert.match(await page.locator('#catalogueRows .entity-type').innerText(),/Recorded evidence:/);assert.match(await page.locator('#catalogueRows .entity-type').innerText(),/LLM-assisted/);
await search.fill('');receipt.checks.push('typed catalogue searches purpose, audience and intended roles separately from recorded evidence');
for(const child of catalogue.entities.filter(entity=>{if(!entity.parent_id)return false;let ancestor=entity;while(ancestor.parent_id)ancestor=catalogue.entities.find(item=>item.id===ancestor.parent_id);return catalogue.view.items.some(item=>item.entity_id===ancestor.id);})){
  await search.fill(child.title);
  assert.equal(await page.locator('[id='+JSON.stringify(child.id)+']').isVisible(),true);
  let parentId=child.parent_id;
  while(parentId){assert.equal(await page.locator('[id='+JSON.stringify(parentId)+']').evaluate(e=>e.open),true);parentId=catalogue.entities.find(entity=>entity.id===parentId).parent_id;}
  assert.deepEqual(await page.locator('#catalogueRows tr:visible').evaluateAll(rows=>rows.map(row=>row.dataset.entityId)),catalogue.entities.filter(entity=>matches(entity,child.title)).map(entity=>entity.id));
}
await search.fill('');
assert.equal(await page.locator('#kuiper').evaluate(e=>e.open),false);
receipt.checks.push('child searches expose parent nests and filter matching catalogue rows');
await page.locator('#identity-registry > summary').click();assert.equal(await page.locator('#identity-registry .launch').getAttribute('href'),'https://ventusltd.github.io/globalgrid2050-ip-and-mac-addresses/');
await page.locator('#kuiper > summary').click();await page.locator('#kuiper .versions > summary').click();assert.match(await page.locator('#kuiper .versions').innerText(),/Archived/i);assert.equal(await page.locator('#archiveLink').getAttribute('href'),catalogue.view.archive_url);receipt.checks.push('identity launch, operative history and archive retained');
await page.locator('#kuiper > summary').click();await page.locator('#identity-registry > summary').click();
await search.evaluate(e=>e.blur());await page.mouse.move(0,0);
assert.equal(await page.locator('.development-track').evaluate(e=>getComputedStyle(e).animationDuration),'24s');
await page.locator('.development-strip').hover();assert.equal(await page.locator('.development-track').evaluate(e=>getComputedStyle(e).animationPlayState),'paused');
await page.mouse.move(0,0);await page.locator('.development-group:not([aria-hidden]) a').first().focus();assert.equal(await page.locator('.development-track').evaluate(e=>getComputedStyle(e).animationName),'none');await page.locator('.development-group:not([aria-hidden]) a').first().evaluate(e=>e.blur());
assert.equal(await page.locator('.development-group[aria-hidden] a').first().getAttribute('tabindex'),'-1');
await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});receipt.checks.push('24-second ticker, hover/focus pause and one keyboard link per destination');
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('.catalogue-scroll').evaluate(e=>getComputedStyle(e).overflowX),'auto');assert(await page.locator('.catalogue-scroll').evaluate(e=>e.scrollWidth>e.clientWidth));await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});receipt.checks.push('390px layout without document overflow');
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.development-track').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await page.locator('.development-group[aria-hidden]').isVisible(),false);receipt.checks.push('reduced motion retains static links');
await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base);await page.waitForSelector('.development-track');
const destination=await page.locator('.development-group[aria-hidden] a').first().getAttribute('href');
await page.route(destination,route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Destination click verified</title>'}));
await page.locator('.development-track').evaluate(e=>{e.style.animation='none';e.style.transform='translateX(-50%)';});
await page.locator('.development-group[aria-hidden] a').first().click();assert.equal(page.url(),destination);receipt.checks.push('visible repeated ticker link really navigates');
await page.route('**/data/active-pages.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Repository',url:'https://github.com/Ventusltd/example'}]})}));
await page.goto(base);await page.waitForSelector('#searchControls:not([hidden])');await page.waitForLoadState('networkidle');assert.equal(await page.locator('.development-strip').count(),0);assert.equal(await page.locator('#nests > details').count(),catalogue.view.items.length);receipt.checks.push('invalid optional app feed leaves searchable nests available');
const fallback=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await fallback.goto(base);assert.equal(await fallback.locator('#catalogueRows tr').count(),firstPage.length);assert.equal(await fallback.locator('#catalogue').isVisible(),true);for(const entity of firstPage){const release=entity.releases.find(r=>r.id===entity.operative_release_id);assert.equal(await fallback.locator('#catalogueRows').getByRole('link',{name:entity.title,exact:true}).getAttribute('href'),release.url);}assert.equal(await fallback.locator('#nests > details').count(),catalogue.view.items.length);assert.equal(await fallback.locator('#kuiper').evaluate(e=>e.open),false);assert.equal(await fallback.locator('#identity-registry .launch').getAttribute('href'),'https://ventusltd.github.io/globalgrid2050-ip-and-mac-addresses/');assert.equal(await fallback.locator('#archiveLink').getAttribute('href'),catalogue.view.archive_url);await fallback.close();receipt.checks.push('static closed nests and archive survive disabled JavaScript');
const paged=await browser.newPage();
const large=structuredClone(catalogue);const largeMetadata=structuredClone(metadata);
for(let i=0;i<presentation.page_size+6;i++){const entity=structuredClone(catalogue.entities[0]);entity.id='pagination-probe-'+i;entity.title='Pagination probe '+i;delete entity.parent_id;large.entities.push(entity);largeMetadata.records[entity.id]=structuredClone(metadata.records[catalogue.entities[0].id]);}
await paged.route('**/data/homepage.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(large)}));
await paged.route('**/data/entity-types.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(largeMetadata)}));
await paged.goto(base);await paged.waitForSelector('#searchControls:not([hidden])');
assert.equal(await paged.locator('#catalogueRows tr').count(),presentation.page_size);
assert.equal(await paged.locator('#cataloguePrevious').isDisabled(),true);
assert.equal(await paged.locator('#catalogueNext').isDisabled(),false);
const ids=()=>paged.locator('#catalogueRows tr').evaluateAll(rows=>rows.map(row=>row.dataset.entityId));
await paged.locator('#catalogueNext').click();assert.deepEqual(await ids(),large.entities.slice(presentation.page_size,2*presentation.page_size).map(e=>e.id));
await paged.locator('#cataloguePrevious').click();assert.deepEqual(await ids(),large.entities.slice(0,presentation.page_size).map(e=>e.id));
await paged.locator('#homepageSearch').fill(large.entities.at(-1).id);assert.deepEqual(await ids(),[large.entities.at(-1).id]);assert.equal(await paged.locator('#catalogueNext').isDisabled(),true);
await paged.locator('#homepageSearch').fill('');assert.deepEqual(await ids(),large.entities.slice(0,presentation.page_size).map(e=>e.id));
while(!await paged.locator('#catalogueNext').isDisabled())await paged.locator('#catalogueNext').click();assert(await paged.locator('#catalogueRows tr').count()<=presentation.page_size);assert((await ids()).includes(large.entities.at(-1).id));
await paged.close();receipt.checks.push('synthetic multi-page catalogue bounds DOM rows, paginates in both directions and searches off-page permanent keys');
const invalidPresentation=await browser.newPage();
await invalidPresentation.route('**/data/presentation.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...presentation,page_size:1000000})}));
await invalidPresentation.goto(base);await invalidPresentation.waitForFunction(()=>document.getElementById('searchStatus').textContent.includes('unavailable'));
assert.equal(await invalidPresentation.locator('#searchControls').isVisible(),false);
assert.equal(await invalidPresentation.locator('.highlight-card').count(),presentation.highlights.length);
assert.equal(await invalidPresentation.locator('#catalogueRows tr').count(),firstPage.length);
await invalidPresentation.close();receipt.checks.push('invalid page-size configuration preserves bounded static fallback');
const unavailable=await browser.newPage();
await unavailable.route('**/data/homepage.json',route=>route.abort('timedout'));
await unavailable.goto(base);await unavailable.waitForFunction(()=>document.getElementById('searchStatus').textContent.includes('unavailable'));
assert.equal(await unavailable.locator('.highlight-card').count(),presentation.highlights.length);
assert.equal(await unavailable.locator('#nests > details').count(),catalogue.view.items.length);
await unavailable.close();receipt.checks.push('unavailable catalogue preserves static highlights and app links');
for(const scenario of ['missing-record','same-size-orphan','invalid-type','unsafe-evidence-url']){
  const badMetadata=await browser.newPage();const unknown=structuredClone(metadata);
  if(scenario==='missing-record')delete unknown.records.kuiper;
  else if(scenario==='same-size-orphan'){unknown.records['unknown-entity']=unknown.records.kuiper;delete unknown.records.kuiper;}
  else if(scenario==='invalid-type')unknown.records.kuiper.type='unrecognized';
  else unknown.records.kuiper.capability_evidence.url='javascript:alert(1)';
  await badMetadata.route('**/data/entity-types.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(unknown)}));
  await badMetadata.goto(base);await badMetadata.waitForFunction(()=>document.getElementById('searchStatus').textContent.includes('unavailable'));
  assert.equal(await badMetadata.locator('#searchControls').isVisible(),false,scenario);
  assert.equal(await badMetadata.locator('#catalogueRows tr').count(),firstPage.length,scenario);
  assert.equal(await badMetadata.locator('.highlight-card').count(),presentation.highlights.length,scenario);
  await badMetadata.close();
}
receipt.checks.push('missing, orphan, unknown-type and unsafe-evidence metadata preserve the static catalogue');
assert.deepEqual(errors,[]);receipt.checks.push('no browser runtime errors');receipt.status='pass';
}catch(error){receipt.status='fail';receipt.error=error.stack;process.exitCode=1;}finally{if(browser)await browser.close();server.close();fs.writeFileSync(path.join(output,'receipt.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt,null,2));}})();
