'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'..');
const catalogue=JSON.parse(fs.readFileSync(path.join(root,'data/homepage.json'),'utf8'));
const output=path.join(root,'browser-evidence');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.json':'application/json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{let browser;const receipt={status:'running',checks:[],source:process.env.GITHUB_SHA||'local'};try{
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.waitForSelector('.build-card');
assert.equal(await page.locator('#nests > details').count(),catalogue.view.items.length);
assert.equal(await page.locator('.build-card').count(),Math.min(3,catalogue.development.length));
assert.equal(await page.locator('.development-group:not([aria-hidden]) a').count(),catalogue.view.items.length+catalogue.development.length);
receipt.checks.push('configured nests, bounded highlights and ticker links');
const search=page.locator('#homepageSearch');assert((await search.boundingBox()).y<(await page.locator('.build-highlights').boundingBox()).y);
await search.fill('factory');assert.equal(await page.locator('.build-card:visible').count(),1);assert.match(await page.locator('.build-card:visible').innerText(),/Inspection connections/);assert.equal(await page.locator('#nests > details:visible').count(),0);assert.match(await page.locator('#searchStatus').innerText(),/1 builds/);
await search.fill('GridAtlas');assert.equal(await page.locator('#nests > details:visible').count(),1);
await search.fill('unlikelynomatch');assert.match(await page.locator('#searchStatus').innerText(),/No matching/);
await search.fill('');assert.equal(await page.locator('#nests > details:visible').count(),catalogue.view.items.length);assert(await page.locator('#kuiper').evaluate(e=>e.open));
receipt.checks.push('top search finds independent build descriptions and restores nests');
await page.locator('#identity-registry > summary').click();assert.equal(await page.locator('#identity-registry .launch').getAttribute('href'),'https://ventusltd.github.io/globalgrid2050-ip-and-mac-addresses/');
await page.locator('#kuiper .versions > summary').click();assert.match(await page.locator('#kuiper .versions').innerText(),/Archived/i);assert.equal(await page.locator('#archiveLink').getAttribute('href'),catalogue.view.archive_url);receipt.checks.push('identity launch, operative history and archive');
await page.locator('.ticker-pause').click();assert.equal(await page.locator('.ticker-pause').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.development-track').evaluate(e=>getComputedStyle(e).animationPlayState),'paused');
assert.equal(await page.locator('.development-group[aria-hidden] a').first().getAttribute('tabindex'),'-1');
await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});receipt.checks.push('ticker pause and one keyboard link per destination');
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});receipt.checks.push('390px layout without document overflow');
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.development-track').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await page.locator('.development-group[aria-hidden]').isVisible(),false);receipt.checks.push('reduced motion retains static links');
await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base);await page.waitForSelector('.development-track');
const destination=await page.locator('.development-group[aria-hidden] a').first().getAttribute('href');
await page.route(destination,route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Destination click verified</title>'}));
await page.locator('.development-track').evaluate(e=>{e.style.animation='none';e.style.transform='translateX(-50%)';});
await page.locator('.development-group[aria-hidden] a').first().click();assert.equal(page.url(),destination);receipt.checks.push('visible repeated ticker link really navigates');
const fallback=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await fallback.goto(base);assert.equal(await fallback.locator('#nests > details').count(),catalogue.view.items.length);assert.equal(await fallback.locator('#identity-registry .launch').getAttribute('href'),'https://ventusltd.github.io/globalgrid2050-ip-and-mac-addresses/');await fallback.close();receipt.checks.push('static launch links survive disabled JavaScript');
assert.deepEqual(errors,[]);receipt.checks.push('no browser runtime errors');receipt.status='pass';
}catch(error){receipt.status='fail';receipt.error=error.stack;process.exitCode=1;}finally{if(browser)await browser.close();server.close();fs.writeFileSync(path.join(output,'receipt.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt,null,2));}})();
